---
- name: add an apt signing key for elasticsearch
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: add elasticsearch's repository into sources list.
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main' state=present

- name: install elasticsearch
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - elasticsearch

- name: elasticsearch is running and enabled
  service: name=elasticsearch state=running enabled=yes
